### PR TITLE
Add noindex for nonredirect page

### PR DESCRIPTION
**Pull request by Sreejith-Websphere**

### CODE REVIEW

**Comment by kinueng** [comment]
We need to rethink how to approach marking the iframes as no index. Manually adding the `noindex` element will not be sustainable for future new javadocs that are generated using the JDK CLI command `javadoc`.

**Comment by kinueng** [comment]
There is another question of why there are other commits being included in this PR. Will need to investigate if the `draft` `staging` `prod` branches are out of sync.

Update: `draft` is missing some commits, fixing using this PR https://github.com/OpenLiberty/docs-javadoc/pull/33

**Comment by dmuelle** [comment]
is this PR still needed?

**Comment by dmuelle** [comment]
closing this as it's almost a year old and showing many conflicts

**Pull request closed without merging**
