### PR TITLE
Check in MicroProfile 6.0 javadoc

### PR DESCRIPTION
**Pull request by steven1046**
Source code used: https://github.com/eclipse/microprofile/releases
Bugs fixed and delivered to MicroProfile 6.0 here: https://github.com/eclipse/microprofile-metrics/pull/765

### CODE REVIEW

**Comment by kinueng** [comment]
Hi @steven1046
Should we open another issue to regenerate MP6.0 javadocs to pick up the `microprofile-metrics-5.0.1` released per this [comment](https://github.com/eclipse/microprofile-metrics/pull/765#issuecomment-1412722287)? 
Did you generate the javadocs in this PR with the fix from https://github.com/eclipse/microprofile-metrics/pull/765?

**Comment by steven1046** [comment]
The javadoc here is generated using the source from https://github.com/eclipse/microprofile-metrics/releases/tag/5.0.0 and applying the fixes manually. The fixes i made to their repo aren't delivered yet in a 5.0.1 release, which may be soon but the date is unknown.

**Comment by steven1046** [comment]
We can either wait for an official 5.0.1 release including the fixes, or deliver these now and incorporate the fixes. I had to apply 1 more manual fix in this PR than what is in https://github.com/eclipse/microprofile-metrics/pull/765. The reason for the 1 more manual fix is that running my javadoc command locally gave me an error and made me change the [RegistryType](https://github.com/eclipse/microprofile-metrics/blob/master/api/src/main/java/org/eclipse/microprofile/metrics/annotation/RegistryType.java#L64) link from `{@link MetricRegistry.Type}` to `{@link org.eclipse.microprofile.metrics.MetricRegistry.Type}` for it to have 0 errors and another person did not have that error with the same Java version:
```
openjdk 17.0.5 2022-10-18
IBM Semeru Runtime Open Edition 17.0.5.0 (build 17.0.5+8)
Eclipse OpenJ9 VM 17.0.5.0 (build openj9-0.35.0, JRE 17 Mac OS X amd64-64-Bit Compressed References 20221018_304 (JIT enabled, AOT enabled)
OpenJ9   - e04a7f6c1
OMR      - 85a21674f
JCL      - 32d2c409a33 based on jdk-17.0.5+8)
```.

**Review by kinueng — APPROVED** [review]
OK - I agree with going with a pragmatic approach of fixing up `5.0.0` locally with patches that we expect will be included in `5.0.1`

**Comment by steven1046** [comment]
I can't merge myself. I will work today on creating the .adoc file to house the MP 6.0 javadoc in the docs repo.

**Comment by steven1046** [comment]
The doc page is here: https://github.com/OpenLiberty/docs/pull/6261

**Pull request merged**
