### PR TITLE
Added Frameless javadocs 

### PR DESCRIPTION
**Pull request by SteveSamJacob19**
Even after rebasing to draft, i still see commits that are not created by me, but i think its because of some direct changes to prod without the draft being updated. Can you go through this and see if you can merge it, There are a huge number of files and hence the files changed cant be viewed

### CODE REVIEW

**Comment by dmuelle** [comment]
@SteveSamJacob19 I cant see what files this is trying to pull in but note that we dont publish the javadoc to draft. So your PR might be trying to pull in every release of all Javadoc files in a single PR. We only publish the full javadoc to staging and prod. See the readme for details and let me know if you have any questions:

https://github.com/OpenLiberty/docs-javadoc/tree/prod?tab=readme-ov-file#preparing-open-liberty-api-and-spi-javadoc-files-for-publication

One thing to make sure is that your working branch is based on `prod` and targets staging.

**Comment by SteveSamJacob19** [comment]
@dmuelle i did go through the readme first but i thought that applied only to the version javadocs because when i went through old PRs, i saw that the microprofile javadocs were pushed into draft like [here](https://github.com/OpenLiberty/docs-javadoc/pull/64). Also the draft openliberty.io website used the draft branch of docs-javadoc [here](https://github.com/OpenLiberty/openliberty.io/wiki/Websites-&-branch-breakdown) so im a bit confused on how to proceed here

**Comment by SteveSamJacob19** [comment]
Note: I am adding the Mircroprofile 1.2 - 6.1 , Jakarte EE 9.1-10 and Java EE 7-8 frameless docs and not the API/SPI docs

**Comment by steven1046** [comment]
Since we aren't publishing javadocs to draft, it might be an opportunity to remove them from the draft branch of this repo. @SteveSamJacob19, can you please rebase on prod to deliver into staging?

**Pull request closed without merging**
